### ISSUE TITLE
Transfer to AcornHack Organisation

### ISSUE THREAD

**Issue by eddiejaoude** [KaraMarck/StudyBuddy#1]
Hello,

Can we transfer this to the **AcornHack** Organisation so all the projects can be together? This is the only project not on there.

Thanks :smile: 

https://github.com/AcornHack

**Comment by MarckK** [comment]
Hi Eddie,

Of course!

It is was very nice to meet you at the hackathon.  Thank you for your
commitment to making the hackathon such an amazing experience for the girls!

Best wishes,
Kara

**Comment by eddiejaoude** [comment]
Thank you @KaraMarck and thank you for your kind words! Sorry we didn't get a chance to catch up properly. I heard wonderful things from your team though :wink: .

Hope to see you at another event soon, either AcornHack, WHFNP, EmpowerHack etc ... :smile:

**Comment by MarckK** [comment]
Hi Eddie, I'll be at the next EmpowerHack in April and will hopefully see
you there [image: :smile:]

**Comment by eddiejaoude** [comment]
Great! :+1: . Looking forward to geeking out :smile:

**Comment by MarckK** [comment]
Hi Eddie,

I've made you a collaborator, so I believe you now have direct access to the repo and can make direct pushes.  Is it alright if I leave it to you to pull the StudyBuddy repo into AcornHack Organisation?

**Comment by eddiejaoude** [comment]
Hi @KaraMarck , thanks for adding me as a collaborator, however I will not be able to transfer it to AcornHack, only the owner can do that - I would only be able to take a copy of it either manually or as a fork.

**Comment by eddiejaoude** [comment]
I am just reading the docs, and realised you will not be able to transfer it to the AcornHack organisation either.

May be it is best if you transfer it to me, then I can transfer it to AcornHack? 

Here are the documentation from GitHub https://help.github.com/articles/transferring-a-repository/#transferring-between-user-accounts

**Comment by MarckK** [comment]
Yes, I was having trouble transferring it to AcornHack; hopefully, I have
now transferred it to you :)

**Comment by eddiejaoude** [comment]
Great, received it!

**Comment by eddiejaoude** [comment]
I have transferred it to AcornHack https://github.com/AcornHack/StudyBuddy

**Comment by eddiejaoude** [comment]
I will close this ticket now :smile:

**Comment by eddiejaoude** [comment]
I have added the **StudyBuddy** team to the new **StudyBuddy** repo ... so people can continue to contribute - if I need to add anyone else let me know :smile:

**Comment by MarckK** [comment]
Thank you Eddie; how much effort you have put into supporting AcornHack is
wonderful!

**Comment by eddiejaoude** [comment]
Thanks @KaraMarck . Same to you & everyone else :+1:
